name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
        phpunit-versions: [ 'latest' ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.2'
            phpunit-versions: '8.5.21'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install php dependencies
        run: composer install --prefer-dist

      - name: Run Tests
        run: vendor/bin/phpunit -c phpunit.xml.dist tests
